server:
  port: 8092
  
spring:
  application:
    name: authentication-service
  cloud:
    consul:
      host: localhost
      port: 8500

security:
  jwt:
    token:
      secret-key: asdfSFS34wfsdfsdfSDSD32dfsddDDerQSNCK34SOWEK5354fdgdf4
#      expire-length: 7776000000 # 5 Day 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds
      expire-length: 3600000
      
management:
  security:
    enabled: false